### ISSUE TITLE
Cannot use Ceph cli from other mons other than mon[0]

### ISSUE THREAD

**Issue by fmount** [fmount/tripleo-ceph#21]
Using cephadm we run the playbook, the bootstrap command and the other tasks using the first mon.
After the Ceph cluster has been deployed I see:

```
 services:
    mon: 5 daemons, quorum controller-0,ceph-0,ceph-1,controller-1,controller-2 (age 10m)
    mgr: mgr.controller-1.dbtglp(active, since 54s), standbys: mgr.controller-0.dpkqqb
    mds:  3 up:standby
    osd: 8 osds: 8 up (since 4h), 8 in (since 4h); 154 remapped pgs
```

but, trying to run the following from another monitor:

```
[heat-admin@controller-1 ~]$ sudo podman run --rm -it --net=host --ipc=host -v /etc/ceph:/etc/ceph:z docker.io/ceph/ceph:v15 ceph --fsid 2312eef6-a6f7-11ea-80a2-24420039d6e3 -c /etc/ceph/ce
ph.conf -k /etc/ceph/ceph.client.openstack.keyring  -s
```
the following error is returned:

```
[errno 5] RADOS I/O error (error connecting to the cluster)
```

Looking at ceph.conf I see:

```
[heat-admin@controller-1 ~]$ cat /etc/ceph/ceph.conf
# minimal ceph.conf for 2312eef6-a6f7-11ea-80a2-24420039d6e3
[global]
        fsid = 2312eef6-a6f7-11ea-80a2-24420039d6e3
        mon_host = [v2:172.16.11.153:3300/0,v1:172.16.11.153:6789/0]
```
where `172.16.11.153` is the ip address on the StorageNetwork of the first mon (used by the bootstrap command).

Not sure if it's expected to see the config updated by `ceph orch` when a new node/service is added.
